db_dsn: "root:root@tcp(127.0.0.1:13306)/MySQLLoadTester?parseTime=true&tls=false"
queries_data_source:
  type: db
  db:
    input_file: "queries.txt"
    dsn: "root:root@tcp(127.0.0.1:13306)/MySQLLoadTester?parseTime=true&tls=false"
    fingerprint_weights_query: |
      WITH queryFingerprintTotal AS (
        SELECT COUNT(*) AS c FROM QueryFingerprint
      )
      SELECT
        qf2.Hash AS Hash,
        COUNT(*) AS Count,
        qft.c AS Total,
        CAST(COUNT(*) AS DECIMAL(10,4)) / qft.c * 100 AS Weight
      FROM QueryFingerprint qf2
      CROSS JOIN queryFingerprintTotal qft ON 1=1
      GROUP BY qf2.Hash
    queries_fetch_query: |
      select
        q.Offset, q.Length
      from
        Query q
      inner join QueryFingerprint qf on q.FingerprintHash = qf.Hash
      where
        qf.Hash = {{.Hash}}
      limit 1

    queries_ids_fetch_query: |
      select
        ID,
        FingerprintHash
      from
        Query

count: -1
run_mode: random
reporting:
  file: /dev/stdout
  format: human
concurrency: 100
metrics:
  enabled: true
  addr: ":2112"
