db_dsn: "root:root@tcp(127.0.0.1:13306)/MySQLLoadTester?parseTime=true&tls=false"

queries_data_source:
  type: file
  file:
    input_file: "queries.bin"
count: -1
run_mode: random
reporting:
  file: /dev/stdout
  format: human
concurrency: 200
metrics:
  enabled: true
  addr: ":2112" # <-- Tambahkan address di sini jika belum ada
