db_dsn: "root:root@tcp(127.0.0.1:13306)/MySQLLoadTester?parseTime=true&tls=false"

queries_data_source:
  type: file
  file:
    input_file: "queries.bin"

count: -1
run_mode: random
concurrency: 200
metrics:
  enabled: true
  addr: ":2112"
