CREATE TABLE Query (
    ID BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    -- Query TEXT NOT NULL,
    `Offset` BIGINT UNSIGNED NOT NULL,
    `Length` INT UNSIGNED NOT NULL,
    `Hash` BIGINT UNSIGNED NOT NULL,
    -- `Count` INT UNSIGNED NOT NULL DEFAULT 1,
    FingerprintHash BIGINT UNSIGNED NOT NULL
    UNIQUE KEY `idx_hash` (`Hash`)
);
